import path from 'node:path';
import {writeFile} from 'node:fs/promises';
import type {GraphicsPlan} from '../schemas/graphics-plan';
import {resolveTokens} from '../src/tokens';
import {defaultPairing,fontPairings} from '../src/tokens/typography';
import {cueText} from '../src/components/shared';
import {atomic} from './io';
export async function writeReviewArtifacts(project:string,p:GraphicsPlan){
 const t=resolveTokens(p.preset,p.fontPairing),pairing=p.fontPairing??defaultPairing[p.preset];
 await atomic(path.join(project,'style-spec.json'),{preset:p.preset,fontPairing:pairing,requestedPairing:fontPairings[pairing].requested,substitutions:fontPairings[pairing].substitutions,tokens:t,platform:p.platform,width:p.width,height:p.height,fps:p.fps});
 await atomic(path.join(project,'asset-report.json'),{fonts:t.fonts.faces.map(f=>({...f,path:`public/fonts/${f.file}`,license:'SIL OFL 1.1'})),assets:p.assets,sfx:p.audio.sfx.map(s=>({...s,license:'CC0-1.0',credit:'Original procedural SFX generated by this repository'})),source:'User-provided locked source; ownership and distribution rights remain with the user.'});
 const escape=(s:string)=>s.replaceAll('|','\\|').replaceAll('\n',' '),time=(f:number)=>(f/p.fps).toFixed(3)+'s';
 const rows=p.cues.map(c=>`| ${time(c.startFrame)}–${time(c.endFrame)} | ${c.component} | ${escape(cueText(c)||'Visual layer')} | ${escape(c.reason)} | ${escape(c.source.reference)} |`);
 await writeFile(path.join(project,'cue-sheet.md'),`# ${p.slug} cue sheet\n\nFrames are authoritative; times are display-only.\n\n| Time | Type | Text | Why | Evidence |\n| --- | --- | --- | --- | --- |\n${rows.join('\n')}\n`);
}
